apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
  labels:
    app: iris-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
        - name: iris-api
          image: 349865279621.dkr.ecr.us-west-2.amazonaws.com/iris-api:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
